language: node_js
node_js:
  - 10

script:
 - echo "Deploy!!"

install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --project recruit-5fa61 --token 1/AWu2T4kk1ML3BxuCtQfgWphvEJ6gDL2Wb__K8r-z7ic
